name: "CI"

on:
  pull_request:
  push:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check

  tests:
    name: ${{ matrix.os }} / Julia ${{ matrix.test_depot }}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # macos-latest
        test_depot:
        - "1.8.3"
        - "1.6.6"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Run julia2nix
      run: |
        cd test_depots/${{matrix.test_depot}}
        nix run ..
    - name: Run nix-build
      run: |
        cd test_depots/${{matrix.test_depot}}
        export NIX_PATH="nixpkgs=$(nix run .#nixpkgsPath)"
        nix-build .
    - name: Verify packages work
      run: |
        cd test_depots/${{matrix.test_depot}}
        export NIX_PATH="nixpkgs=$(nix run .#nixpkgsPath)"
        nix-build .
        ./result/bin/julia ./test.jl
